# Generated by Django 2.2.1 on 2019-09-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodstype',
            name='type_picture',
        ),
    ]
