# Generated by Django 2.2.1 on 2019-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_remove_goodstype_type_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='type_picture',
            field=models.ImageField(default='images/03.jpg', upload_to='images'),
        ),
    ]
