# Generated by Django 2.2.1 on 2019-09-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_goodstype_type_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_description',
            field=models.TextField(default='超级好吃!!!!!!!'),
        ),
    ]
