# Generated by Django 2.2.1 on 2019-09-27 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_goods_goods_description'),
        ('Buyer', '0003_orderinfo_goods_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='goods_price',
            field=models.FloatField(verbose_name='商品单价'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.IntegerField(verbose_name='商品数量')),
                ('goods_price', models.FloatField(verbose_name='商品单价')),
                ('goods_total', models.FloatField(verbose_name='商品小计')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.Goods')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
